---
abstract: 'API for Kiwisolver constraint solver'
author:
  - 'Zakariyya Mughal <zmughal@cpan.org>'
build_requires:
  Data::Perl: '0'
  MooX::HandlesVia: '0'
  MooX::InsideOut: '0'
  Mu: '0'
  Path::Tiny: '0'
  SVG: '0'
  Test::Most: '0'
  aliased: '0'
  constant: '0'
  lib: '0'
  perl: '5.008'
configure_requires:
  Alien::Kiwisolver: '0'
  ExtUtils::MakeMaker: '0'
  List::UtilsBy: '0'
  Modern::Perl: '0'
  XS::Framework: '0'
  perl: '5.004'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.029, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Graphics-Layout-Kiwisolver
no_index:
  directory:
    - eg
    - examples
    - inc
    - share
    - t
    - xt
requires:
  XS::Framework: '0'
  XS::Loader: '0'
  overload: '0'
  perl: '5.008'
  strict: '0'
  warnings: '0'
resources:
  homepage: https://github.com/PerlGfx/p5-Graphics-Layout-Kiwisolver
  repository: https://github.com/PerlGfx/p5-Graphics-Layout-Kiwisolver.git
version: '0.002'
x_generated_by_perl: v5.26.1
x_serialization_backend: 'YAML::Tiny version 1.73'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
